# Generated by Django 5.1.1 on 2025-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_path', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('application_type', models.IntegerField(blank=True, choices=[(0, 'Reference'), (1, 'Image'), (2, 'Video')])),
                ('application_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
