# Generated by Django 5.1.1 on 2025-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_result_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_backgrounds/'),
        ),
    ]
