# Generated by Django 5.1.1 on 2025-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_gender_split',
            field=models.BooleanField(default=False),
        ),
    ]
