# Generated by Django 5.1.1 on 2025-02-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_test_has_gender_split'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
